bracketSpacing: true
jsxBracketSameLine: false
printWidth: 100
semi: true
singleQuote: true
tabWidth: 4
trailingComma: es5
useTabs: true
overrides:
  - files: "**/*.md"
    options:
    tabWidth: 2
    useTabs: false
  - files: "**/*.yaml"
    options:
    tabWidth: 2
    useTabs: false
