# Hugo configuration

disableFastRender: true
enableEmoji: true
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
publishDir: 'dist'
resourceDir: '.resources'

# Site configuration

baseURL: 'https://das-habitat.de'
defaultContentLanguage: 'de'
languages:
  de:
    weight: 1
languageCode: 'de-de'
sitemap:
  changefreq: 'monthly'
  filename: 'sitemap.xml'
theme:
  - 'hugo-debugprint'
  - 'habitat'
title: 'Das Habitat'

# Menus

menu:
  courses:
    - identifier: index
      name: Übersicht
      url: /kurse/
      weight: -100

# Taxonomies

preserveTaxonomyNames: true
taxonomies:
  category: categories
  tag: tags
  kurs: kurse

# Global attributes

Params:
  # Using staticforms.xyz
  forms:
    contact:
      email: kontakt+formular@das-habitat.de
      accessKey: 8b79d8d6-3a17-4148-9da1-8bc9c184cad8
      redirect: /danke
