baseURL = "http://das-habitat.de"
languageCode = "de-de"
title = "Das Habitat"
theme = "habitat"
publishDir = "dist"
enableRobotsTXT = true
defaultContentLanguage = "de"
enableEmoji = true
resourceDir = ".resources"
