baseURL: 'https://das-habitat.de'
languageCode: 'de-de'
title: 'Das Habitat'
theme:
  - 'hugo-debugprint'
  - 'habitat'
publishDir: 'dist'
enableRobotsTXT: true
defaultContentLanguage: 'de'
enableEmoji: true
resourceDir: '.resources'

sitemap:
  changefreq: 'monthly'
  filename: 'sitemap.xml'

markup:
  goldmark:
    renderer:
      unsafe: true

preserveTaxonomyNames: true

disableFastRender: true

Params:
  # Using staticforms.xyz
  forms:
    contact:
      email: kontakt+formular@das-habitat.de
      accessKey: 8b79d8d6-3a17-4148-9da1-8bc9c184cad8
      redirect: /danke
