baseURL = "http://das-habitat.de"
languageCode = "de-de"
title = "Das Habitat"
theme = ["hugo-debugprint", "habitat"]
publishDir = "dist"
enableRobotsTXT = true
defaultContentLanguage = "de"
enableEmoji = true
resourceDir = ".resources"
EnableGitInfo = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
