title: Site
unlisted: true

tabs:
  pages:
    label:
      de: Seiten
      en: Pages
    sections:
      drafts:
        type: pages
        status: draft
        headline:
          de: Entwürfe
          en: Drafts
      published:
        type: pages
        status: published
        headline:
          de: Veröffentlicht
          en: Published
        sortable: true
  menus:
    label:
      de: Einstellungen
      en: Settings
    fields:
      menus:
        label:
          de: Menüs
          en: Menus
        type: structure
        fields:
          menuHeadline:
            type: text
            label: Menu headline
          menuItems:
            type: pages
            label: Menu item
            status: all

      # colorextractor:
      #   label:
      #     de: Farbauszüge
      #     en: Color extractor
      #   type: colorextractor
      #   help:
      #     de: |
      #       Die Seite nutzt die dominanten Farben von Bildern als Platzhalter während des Ladevorgangs.
      #       Für manuell via SFTP hochgeladene Bilder müssen die Farben nachträglich ermittelt werden.
      #     en: |
      #       The site uses dominant colors as placeholders while images are loaded.
      #       Manully uploaded images via SFTP require manual extraction of colors.
