title: Site
unlisted: true

tabs:
  pages:
    label:
      de: Seiten
      en: Pages
    sections:
      drafts:
        type: pages
        status: draft
        headline:
          de: Entwürfe
          en: Drafts
      published:
        type: pages
        status: unlisted,listed
        headline:
          de: Veröffentlicht
          en: Published
  menus:
    label:
      de: Menüs
      en: Menus
    fields:
      menus:
        type: structure
        fields:
          menuHeadline:
            type: text
            label: Menu headline
          menuItems:
            type: pages
            label: Menu item
