name: CI

on:
  push:
    branches:
      - kirby
jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Executing `deploy.sh` on our host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sh ~/deploy.sh
